Repository joinmarket-webui/jam, pull requests merged in 2022-08, with the labels that each got.

#436 feat(settings): add link to Matrix and Jam's twitter
  public/sprite.svg
  src/components/App.jsx
  src/components/Onboarding.jsx
  src/components/Settings.jsx
  src/i18n/locales/en/translation.json
Labels: enhancement

#437 feat(settings): add links to docs
  src/components/Onboarding.jsx
  src/components/Settings.jsx
  src/i18n/locales/en/translation.json
Labels: documentation, enhancement

#433 feat: prevent address reuse on Jam page
  src/components/Jam.jsx
  src/i18n/locales/en/translation.json
Labels: enhancement

#439 fix: size of docs icon in settings
  public/sprite.svg
  src/components/Settings.jsx
Labels: UI/UX

#432 fix: text and border colors after bootstrap update
  src/components/DisplayBranch.module.css
  src/components/DisplayBranch.tsx
  src/index.css
Labels: bug, UI/UX

#431 fix: invalid DOM property 'class' on Earn page
  src/components/Earn.jsx
Labels: bug

#396 regtest: setup with local tor in container
  docker/regtest/docker-compose.yml
  docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/directory_node/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/latest/autostart
  docker/regtest/dockerfile-deps/joinmarket/latest/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/latest/jam-entrypoint.sh
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/tor.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/torrc
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/default.cfg
Labels: devtools

#422 feat: Orderbook
  src/components/Earn.jsx
  src/components/Orderbook.module.css
  src/components/Orderbook.tsx
  src/constants/features.ts
  src/i18n/locales/en/translation.json
  src/index.css
  src/libs/JmObwatchApi.ts
  src/setupProxy.js
Labels: enhancement, concept

#430 feat: utxo list
  package-lock.json
  package.json
  public/sprite.svg
  src/components/CurrentWalletMagic.jsx
  src/components/DisplayAccountsOverlay.module.css
  src/components/DisplayAccountsOverlay.tsx
  src/components/SegmentedTabs.module.css
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jar_details/UtxoList.module.css
  src/components/jar_details/UtxoList.tsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: enhancement

#442 fix: color of light-button in dark mode
  src/index.css
Labels: bug, UI/UX

#443 refactor: remove advanced wallet mode
  src/components/App.jsx
  src/components/CurrentWalletAdvanced.module.css
  src/components/CurrentWalletAdvanced.test.tsx
  src/components/CurrentWalletAdvanced.tsx
  src/components/DisplayAccountUTXOs.jsx
  src/components/DisplayAccounts.jsx
  src/components/DisplayUTXOs.jsx
  src/components/MainWalletView.jsx
  src/components/MainWalletView.module.css
  src/components/Send.jsx
  src/components/Settings.jsx
  src/components/Settings.test.jsx
  src/components/fb/utils.ts
  src/components/jar_details/DisplayBranch.module.css
  src/components/jar_details/DisplayBranch.tsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/context/SettingsContext.jsx
  src/i18n/locales/en/translation.json
Labels: tech dept

#447 fix: cheatsheet icon
  public/sprite.svg
  src/components/App.jsx
Labels: UI/UX

#434 feat: ability to sort and filter orderbook
  src/components/Cheatsheet.module.css
  src/components/Cheatsheet.tsx
  src/components/EarnReport.module.css
  src/components/EarnReport.tsx
  src/components/Orderbook.module.css
  src/components/Orderbook.tsx
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
  src/i18n/locales/en/translation.json
  src/index.css
  src/libs/JmObwatchApi.ts
Labels: enhancement

#445 feat: remove feature flag and enable orderbook for all users
  src/components/Earn.jsx
  src/constants/features.ts
Labels: enhancement

#446 feat: payment confirm modal
  src/components/Send.jsx
  src/components/Send.module.css
  src/i18n/locales/en/translation.json
Labels: enhancement, UI/UX

#449 fix: accordion bg color
  src/components/jar_details/JarDetailsOverlay.module.css
Labels: UI/UX

#450 feat: human readable locktime duration for fidelity bonds
  src/components/fb/CreateFidelityBond.jsx
  src/components/fb/ExistingFidelityBond.jsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/fb/utils.test.ts
  src/components/fb/utils.ts
  src/i18n/locales/en/translation.json
Labels: UI/UX

#452 fix: remove logs
  src/components/fb/ExistingFidelityBond.jsx
Labels: tech dept

#451 feat: add sorting and filtering to earn report
  src/components/EarnReport.module.css
  src/components/EarnReport.test.tsx
  src/components/EarnReport.tsx
  src/i18n/locales/en/translation.json
  src/libs/JmWalletApi.ts
Labels: UI/UX

#453 chore(release): prepare v0.0.10
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#460 regtest: rename default wallet to Satoshi
  CONTRIBUTING.md
  docker/regtest/common.sh
  docker/regtest/fund-wallet.sh
  docker/regtest/init-setup.sh
  docker/regtest/readme.md
Labels: devtools

#456 fix: pass api token to session request
  src/context/ServiceInfoContext.tsx
  src/context/WalletContext.tsx
  src/libs/JmWalletApi.ts
  src/session.ts
Labels: bug

#457 fix: pass mixdepth prop as number in request body
  src/libs/JmWalletApi.ts
Labels: bug

#458 fix: serialize values of `/maker/start` request body as strings
  docker/regtest/init-setup.sh
  src/libs/JmWalletApi.ts
Labels: bug

#466 dev: install gpg in regtest containers
  docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
Labels: dependencies

#464 ui: remove column 'fee' from Earn Report
  src/components/EarnReport.tsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#462 fix: refresh orderbook
  src/components/Orderbook.tsx
  src/libs/JmObwatchApi.ts
Labels: bug

#463 feat: click on active "joining" icon opens relevant screen
  src/components/ActivityIndicators.jsx
  src/components/Navbar.jsx
  src/context/ServiceInfoContext.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
  src/libs/JmWalletApi.ts
Labels: UI/UX

#472 feat: highlight own orders in orderbook
  src/components/Earn.jsx
  src/components/Orderbook.module.css
  src/components/Orderbook.tsx
  src/i18n/locales/en/translation.json
Labels: enhancement, concept, UI/UX

#467 dev: bullseye as base image for regtest containers
  docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
Labels: dependencies, devtools

#470 refactor: leverage session request for polling schedule
  src/components/Jam.jsx
  src/i18n/locales/en/translation.json
Labels: performance

#474 fix: re-add Joining icon
  src/components/Navbar.jsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: UI/UX

#471 fix: proper margin for sweep button on invalid inputs
  src/components/Send.module.css
Labels: bug, UI/UX

#475 feat: rename "Joining" to "Jamming"
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: UI/UX

#476 feat: colored jars with names
  public/sprite.svg
  src/components/Send.jsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jars/Jar.module.css
  src/components/jars/Jar.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: UI/UX

#477 refactor: externalize Footer component
  src/components/App.jsx
  src/components/Footer.jsx
Labels: refactoring

#461 feat: show active offers
  src/components/Earn.jsx
  src/components/Earn.module.css
  src/i18n/locales/en/translation.json
  src/libs/JmWalletApi.ts
Labels: enhancement, UI/UX

#459 ui: add table pagination
  src/components/EarnReport.tsx
  src/components/Orderbook.tsx
  src/components/TablePagination.module.css
  src/components/TablePagination.tsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jar_details/UtxoList.tsx
  src/i18n/locales/en/translation.json
Labels: UI/UX
