Repository joinmarket-webui/jam, pull requests merged in 2022-06, with the labels that each got.

#303 fix: less vertical padding of main container on mobile screens
  src/components/App.jsx
Labels: UI/UX

#293 ui: cheatsheet optimization
  src/components/Cheatsheet.module.css
  src/components/Cheatsheet.tsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: UI/UX

#292 chore: dependencies update
  package-lock.json
  package.json
  src/setupTests.js
Labels: dependencies

#291 docs: describe 'common flow' in regtest readme
  docker/regtest/readme.md
Labels: documentation

#295 ui: add hint about creating wallet duration
  src/components/CreateWallet.jsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#297 fix: prevent unnecessary wallet info requests
  src/context/WalletContext.tsx
  src/libs/JmWalletApi.ts
Labels: bug, performance

#298 fix: prevent unnecessary session requests
  src/context/ServiceInfoContext.tsx
Labels: bug, performance

#299 Fetch config values only once per wallet session
  src/components/Send.jsx
  src/context/ServiceConfigContext.tsx
  src/context/WalletContext.tsx
  src/index.tsx
  src/testUtils.tsx
Labels: tech dept, performance

#300 fix: loading state on Send page
  src/components/Send.jsx
Labels: bug

#301 ui: blur Send form if service is running
  src/components/Send.jsx
  src/components/Send.module.css
Labels: UI/UX

#306 docs: update dev setup readme
  docker/regtest/readme.md
Labels: documentation

#305 feat: enable report overlay
  src/components/Earn.jsx
Labels: enhancement

#304 ui: Earn screen figma alignment
  src/components/Earn.jsx
  src/components/Earn.module.css
  src/components/Receive.jsx
  src/components/Receive.module.css
  src/components/SegmentedTabs.module.css
  src/components/SegmentedTabs.tsx
  src/components/ToggleSwitch.tsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: UI/UX

#296 ui: Settings screen according to figma
  public/sprite.svg
  src/components/CreateWallet.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/Navbar.jsx
  src/components/Settings.jsx
  src/components/Settings.module.css
  src/components/Settings.test.jsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
  src/constants/routes.ts
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: UI/UX

#311 fix: mobile layout issues
  src/components/App.jsx
  src/components/Cheatsheet.module.css
  src/components/PageTitle.jsx
  src/components/Settings.jsx
  src/components/Settings.module.css
  src/index.css
Labels: UI/UX

#241 ui: Wallet Detail Overlay
  public/sprite.svg
  src/components/CopyButton.tsx
  src/components/CurrentWalletMagic.jsx
  src/components/DisplayAccounts.jsx
  src/components/DisplayAccountsOverlay.module.css
  src/components/DisplayAccountsOverlay.tsx
  src/components/DisplayBranch.module.css
  src/components/DisplayBranch.tsx
  src/components/Receive.jsx
  src/components/Send.jsx
  src/components/Send.module.css
  src/context/WalletContext.tsx
  src/hooks/BalanceSummary.ts
  src/i18n/locales/en/translation.json
  src/index.css
Labels: UI/UX

#324 feat: first draft of jars on main wallet screen
  public/sprite.svg
  src/components/App.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/CurrentWalletMagic.module.css
  src/components/DisplayAccountsOverlay.tsx
  src/components/DisplayBranch.tsx
  src/components/Jars.jsx
  src/components/Jars.module.css
  src/components/Layout.jsx
  src/index.css
Labels: UI/UX

#329 fix: css merge error
  src/components/CurrentWalletMagic.module.css
Labels: bug

#335 chore(release): prepare v0.0.7
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#344 feat(jars): add receive shortcut if jar 0 is empty
  src/components/CurrentWalletMagic.jsx
  src/components/Jars.jsx
  src/i18n/locales/en/translation.json
Labels: enhancement

#333 chore: Use `routes` where applicable
  src/components/CreateWallet.jsx
  src/components/Wallet.jsx
  src/components/Wallets.jsx
Labels: enhancement

#332 fix: checked state of ToggleSwitch can be controlled by caller
  src/components/CreateWallet.jsx
  src/components/Jam.jsx
  src/components/Send.jsx
  src/components/Settings.jsx
  src/components/ToggleSwitch.tsx
  src/components/fidelity_bond/FidelityBondDetailsSetupForm.tsx
Labels: UI/UX

#345 feat(jars): destination jar selector on send screen
  package-lock.json
  package.json
  src/components/CurrentWalletMagic.jsx
  src/components/CurrentWalletMagic.module.css
  src/components/JarSelectorModal.jsx
  src/components/JarSelectorModal.module.css
  src/components/Jars.jsx
  src/components/Jars.module.css
  src/components/Send.jsx
  src/components/Send.module.css
  src/components/jars/Jar.module.css
  src/components/jars/Jar.tsx
  src/i18n/locales/en/translation.json
  tsconfig.json
Labels: enhancement, UI/UX

#346 feat(jars): destination jar selector on receive screen
  src/components/Receive.jsx
  src/components/Receive.module.css
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: enhancement, UI/UX

#347 ui: Receive screen advances
  public/sprite.svg
  src/components/Receive.jsx
  src/components/Receive.module.css
Labels: UI/UX

#349 fix: Check preconditions before send request
  src/components/Jam.jsx
  src/components/Send.jsx
  src/hooks/CoinjoinPrecondition.test.tsx
  src/hooks/CoinjoinPrecondition.ts
  src/i18n/locales/en/translation.json
Labels: bug

#354 chore(release): prepare v0.0.8
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#351 refactor: move lock/unlock requests from `Wallet` to `Wallets`
  src/components/App.jsx
  src/components/Settings.jsx
  src/components/Wallet.jsx
  src/components/Wallet.test.jsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
Labels: enhancement

#334 fix: disable 'create wallet' link when unlocking wallet
  src/components/Wallets.jsx
Labels: enhancement
