Repository joinmarket-webui/jam, pull requests merged in 2022-11, with the labels that each got.

#563 ui(orderbook): improve readability with alternating colors
  src/components/Orderbook.module.css
  src/components/Orderbook.tsx
Labels: enhancement, UI/UX

#565 feat: quickly review/adapt fee settings before sweeping
  src/components/Jam.jsx
Labels: concept

#568 ui: improve all overlay content on small screens
  src/components/EarnReport.module.css
  src/components/EarnReport.tsx
  src/components/LogOverlay.module.css
  src/components/LogOverlay.tsx
  src/components/Orderbook.module.css
  src/components/Orderbook.tsx
  src/index.css
Labels: UI/UX

#569 chore(release): v0.1.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
