Repository joinmarket-webui/jam, pull requests merged in 2022-07, with the labels that each got.

#360 ui: min-width for jar balances
  src/components/jars/Jar.module.css
Labels: UI/UX

#358 refactor: pass body of `ConfirmModal` as child node instead of parameter
  src/components/Modal.tsx
  src/components/Settings.jsx
  src/components/Wallets.jsx
Labels: enhancement

#361 feat: move fidelity bonds to earn screen
  public/sprite.svg
  src/components/Alert.jsx
  src/components/App.jsx
  src/components/CurrentWalletAdvanced.tsx
  src/components/Earn.jsx
  src/components/Earn.module.css
  src/components/FidelityBond.module.css
  src/components/FidelityBond.tsx
  src/components/fb/CreateFidelityBond.jsx
  src/components/fb/CreateFidelityBond.module.css
  src/components/fb/ExistingFidelityBond.jsx
  src/components/fb/ExistingFidelityBond.module.css
  src/components/fb/FidelityBondSteps.module.css
  src/components/fb/FidelityBondSteps.tsx
  src/components/fb/LockdateForm.test.tsx
  src/components/fb/LockdateForm.tsx
  src/components/fb/utils.test.ts
  src/components/fb/utils.ts
  src/components/fidelity_bond/AccountCheckbox.tsx
  src/components/fidelity_bond/AccountSelector.tsx
  src/components/fidelity_bond/CheckboxCard.module.css
  src/components/fidelity_bond/CheckboxCard.tsx
  src/components/fidelity_bond/FidelityBondDetailsSetupForm.tsx
  src/components/fidelity_bond/PercentageBar.module.css
  src/components/fidelity_bond/PercentageBar.tsx
  src/components/fidelity_bond/fb_utils.test.ts
  src/components/jars/Jar.module.css
  src/hooks/BalanceSummary.ts
Labels: enhancement, UI/UX

#377 fix: pass body of confirm modal via child node
  src/components/fb/CreateFidelityBond.jsx
Labels: bug

#384 fix: do not show FB create form when maker is running
  src/components/Earn.jsx
Labels: enhancement

#389 fix: encode wallet name param in url path
  src/libs/JmWalletApi.ts
Labels: bug

#390 fix: advanced button wording and behavior
  src/components/Earn.jsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#392 feat: visual warning when selecting non cj-out UTXOs for fidelity bond
  src/components/fb/CreateFidelityBond.jsx
Labels: UI/UX

#394 chore: update readme
  README.md
  docs/assets/screenshot-dark.png
  docs/assets/screenshot-light.png
Labels: documentation

#395 fix: mention jar #0 in preconditions
  src/i18n/locales/en/translation.json
Labels: UI/UX

#393 i18n: extract fidelity bond translation key
  src/components/fb/CreateFidelityBond.jsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/fb/LockdateForm.tsx
  src/i18n/locales/en/translation.json
Labels: tech dept, i18n

#374 regtest: delete wallet lockfiles before startup
  docker/regtest/docker-compose.yml
  docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/directory_node/docker-entrypoint.sh
  docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/latest/jam-entrypoint.sh
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/Dockerfile
Labels: devtools

#403 chore(release): prepare v0.0.9
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#405 docs: update regtest commands in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#410 fix: color of selected collaborators-selector-input
  src/components/Send.jsx
Labels: bug, UI/UX

#409 feat: improve earn report
  src/components/EarnReport.tsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#417 fix: fidelity bonds jar selecotor spacing
  src/components/Balance.jsx
  src/components/fb/FidelityBondSteps.module.css
  src/components/fb/FidelityBondSteps.tsx
Labels: UI/UX

#421 fix: spacing in jar overlay header and `onKeyDown`
  src/components/DisplayAccountsOverlay.module.css
  src/components/DisplayAccountsOverlay.tsx
Labels: UI/UX

#420 fix: do not display freeze info when all utxos have been selected
  src/components/fb/FidelityBondSteps.tsx
Labels: UI/UX

#418 refactor: move filtering for Fidelity Bonds to `WalletContext`
  src/components/CurrentWalletAdvanced.tsx
  src/components/Earn.jsx
  src/components/fb/CreateFidelityBond.jsx
  src/context/WalletContext.tsx
  src/hooks/BalanceSummary.test.tsx
Labels: enhancement, tech dept

#419 refactor: move BalanceSummary to `WalletContext`
  src/components/CurrentWalletMagic.jsx
  src/components/Earn.jsx
  src/components/Jam.jsx
  src/components/Navbar.jsx
  src/components/Receive.jsx
  src/components/Send.jsx
  src/components/fb/FidelityBondSteps.tsx
  src/context/BalanceSummary.test.tsx
  src/context/BalanceSummary.ts
  src/context/WalletContext.tsx
  src/hooks/BalanceSummary.test.tsx
  src/hooks/BalanceSummary.ts
Labels: enhancement, tech dept

#426 feat(cheatsheet): re-word to remove 'yield'
  src/i18n/locales/en/translation.json
Labels: enhancement, UI/UX

#427 feat(cheatsheet): link to jamdocs.org
  src/components/Cheatsheet.tsx
Labels: documentation, UI/UX

#425 deps: update dependencies
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/components/Earn.jsx
  src/components/Earn.module.css
  src/components/Receive.jsx
  src/components/Receive.module.css
  src/components/Send.module.css
  src/index.css
Labels: dependencies

#429 feat(cheatsheet): link to jamdocs.org
  src/components/Cheatsheet.tsx
Labels: documentation, enhancement, UI/UX
