Repository joinmarket-webui/jam, pull requests merged in 2022-10, with the labels that each got.

#529 fix(sweep): wait for scheduler start/stop
  src/components/Jam.jsx
Labels: bug, UI/UX

#522 feat: basic fee settings
  public/sprite.svg
  src/components/Earn.jsx
  src/components/Settings.jsx
  src/components/settings/FeeConfigModal.module.css
  src/components/settings/FeeConfigModal.tsx
  src/context/ServiceConfigContext.tsx
  src/i18n/locales/en/translation.json
  src/index.css
  src/libs/JmWalletApi.ts
  src/utils.test.ts
  src/utils.ts
Labels: enhancement, UI/UX

#531 i18n(orderbook): order -> offer
  src/i18n/locales/en/translation.json
Labels: i18n

#530 fix(sweep): reload wallet info after scheduled sweep
  src/components/Jam.jsx
Labels: bug, UI/UX

#532 feat: display fee settings on Send page
  src/components/Modal.tsx
  src/components/Send.jsx
  src/components/settings/FeeConfigModal.tsx
  src/hooks/Fees.test.ts
  src/hooks/Fees.ts
  src/i18n/locales/en/translation.json
  src/utils.ts
Labels: enhancement, UI/UX

#533 regtest: randomize max fee settings
  docker/regtest/dockerfile-deps/joinmarket/directory_node/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/latest/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/latest/jam-entrypoint.sh
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/default.cfg
Labels: devtools

#536 fix(fees): mitigate construction of non-forwardable transactions
  src/components/settings/FeeConfigModal.tsx
  src/i18n/locales/en/translation.json
Labels: enhancement

#537 chore(release): v0.1.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#521 refactor: jsx to tsx
  src/components/App.tsx
  src/components/Earn.jsx
  src/components/Jam.jsx
  src/components/MainWalletView.jsx
  src/components/Receive.jsx
  src/components/Seedphrase.tsx
  src/components/Send.jsx
  src/components/Settings.jsx
  src/components/Settings.test.jsx
  src/components/settings/SeedModal.tsx
Labels: refactoring

#540 fix: display error message if backend is unreachable
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/Layout.tsx
Labels: bug

#520 regtest: start additional maker service
  docker/regtest/common.sh
  docker/regtest/docker-compose-common.yml
  docker/regtest/docker-compose.yml
  docker/regtest/fund-wallet.sh
  docker/regtest/init-setup.sh
  docker/regtest/readme.md
Labels: devtools

#534 regtest: speed up scheduled sweep for testing
  src/components/Jam.jsx
  src/components/ScheduleProgress.jsx
Labels: devtools

#550 refactor: prepare spending fidelity bond
  src/components/Earn.jsx
  src/components/JarSelectorModal.tsx
  src/components/Jars.jsx
  src/components/MainWalletView.jsx
  src/components/Receive.jsx
  src/components/Send.jsx
  src/components/fb/CreateFidelityBond.jsx
  src/components/fb/ExistingFidelityBond.jsx
  src/components/fb/ExistingFidelityBond.tsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/fb/utils.ts
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jar_details/UtxoList.tsx
  src/components/jars/Jar.tsx
  src/context/WalletContext.tsx
  src/globals.d.ts
  src/hooks/CoinjoinRequirements.ts
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: bug, refactoring

#549 fix: do not enable debug features on `npm start`
  CONTRIBUTING.md
  docker/regtest/readme.md
  docs/developing.md
  package.json
  src/components/CreateWallet.jsx
  src/components/CreateWallet.test.jsx
  src/constants/debugFeatures.ts
  src/constants/features.ts
Labels: concept

#555 build(deps): update dependencies
  package-lock.json
  package.json
  src/components/Orderbook.tsx
  src/components/settings/FeeConfigModal.tsx
Labels: dependencies
