Repository joinmarket-webui/jam, pull requests merged in 2022-02, with the labels that each got.

#39 feat: Adapt favicon color based on system theme
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.svg
  public/index.html
Labels: enhancement

#38 feat: do not autocomplete password when creating wallet
  src/components/CreateWallet.jsx
Labels: enhancement

#45 cleanup: remove broken websocket connection
  src/components/App.jsx
Labels: bug

#53 fix: brighten loading indicator in dark theme
  src/index.css
Labels: enhancement

#52 fix: hidden balance icon alignment and size
  src/components/Balance.jsx
Labels: enhancement

#51 feat: privacy levels
  public/sprite.svg
  src/components/App.jsx
  src/components/CurrentWalletAdvanced.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/DisplayAccounts.jsx
  src/components/Receive.jsx
  src/components/Settings.jsx
  src/context/SettingsContext.jsx
  src/index.css
Labels: enhancement

#62 feat: update create wallet flow
  public/sprite.svg
  src/components/CreateWallet.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/PageTitle.jsx
  src/index.css
Labels: enhancement

#63 feat: fancy toggle switch
  src/components/CreateWallet.jsx
  src/components/ToggleSwitch.jsx
  src/components/ToggleSwitch.module.css
Labels: enhancement

#71 feat: improve wording in settings
  src/components/Settings.jsx
Labels: enhancement

#54 feat: onboarding screen
  public/sprite.svg
  src/components/App.jsx
  src/components/Onboarding.jsx
  src/context/SettingsContext.jsx
Labels: enhancement

#64 feat: update wallets page
  src/components/Wallet.jsx
  src/components/Wallets.jsx
  src/index.css
Labels: enhancement

#84 fix: extract error message of text/html response
  src/components/Send.jsx
Labels: enhancement, UI/UX

#85 feat: update receive page
  public/sprite.svg
  src/components/Receive.jsx
  src/index.css
Labels: enhancement, UI/UX

#89 fix: navigate to root on unmapped path
  src/components/App.jsx
Labels: bug

#82 feat: update earn page
  src/components/App.jsx
  src/components/Earn.jsx
  src/components/Send.jsx
  src/components/ToggleSwitch.jsx
  src/index.css
Labels: enhancement, UI/UX

#91 fix warnings during build
  src/components/App.jsx
  src/components/Onboarding.jsx
Labels: bug, security

#92 feat: add alpha disclaimer
  src/components/App.jsx
  src/index.css
Labels: enhancement, UI/UX, security

#93 fix: condition check during wallet confirmation
  src/components/CreateWallet.jsx
Labels: bug

#97 fix: footer spacing and links
  src/components/App.jsx
Labels: bug

#102 feat: ability for reverse proxy to enforce own auth scheme
  src/libs/JmWalletApi.js
  src/setupProxy.js
Labels: concept, security

#104 fix: enable fetching manifest with credentials
  public/index.html
Labels: bug

#103 docs: add automated changelog generation
  CHANGELOG.md
  package-lock.json
  package.json
  scripts/changelog.mjs
Labels: documentation, concept, devtools

#106 feat: make balance hideable on click
  src/components/CurrentWalletMagic.jsx
Labels: UI/UX

#109 fix: improve onboarding mobile layout
  src/components/App.jsx
  src/components/Onboarding.jsx
  src/index.css
Labels: UI/UX

#108 feat: update wallets page
  src/components/App.jsx
  src/components/PageTitle.jsx
  src/components/Wallet.jsx
  src/components/Wallets.jsx
Labels: enhancement, concept, UI/UX

#110 feat: freeze/unfreeze utxos and fix style on dark theme
  src/components/DisplayAccountUTXOs.jsx
  src/components/DisplayAccounts.jsx
  src/components/DisplayUTXOs.jsx
  src/libs/JmWalletApi.js
Labels: bug, enhancement, concept, UI/UX

#112 devtools: document and further automate release process
  .npmrc
  RELEASING.md
  package.json
  scripts/changelog.mjs
Labels: concept, devtools

#113 chore(release): prepare v0.0.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#99 dev: use joinmarket-webui-dev-standalone in regtest setup
  docker/regtest/docker-compose.yml
  docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/latest/autostart
  docker/regtest/dockerfile-deps/joinmarket/latest/docker-entrypoint.sh
  docker/regtest/dockerfile-deps/joinmarket/latest/exec-wrapper.sh
  docker/regtest/dockerfile-deps/joinmarket/latest/set-wallet.sh
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/jmwalletd.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/ob-watcher.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/yg-privacyenhanced.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/yield-generator-basic.conf
  docker/regtest/dockerfile-deps/joinmarket/v0.9.3/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/v0.9.3/autostart
  docker/regtest/dockerfile-deps/joinmarket/v0.9.3/supervisor-conf/jmwalletd.conf
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/default.cfg
  docker/regtest/init-setup.sh
  docker/regtest/readme.md
Labels: enhancement, devtools

#116 Take minimum_makers config var value into account on Send page
  src/components/Send.jsx
  src/libs/JmWalletApi.js
Labels: bug

#119 docs: add contribution guide and refactor docs
  CONTRIBUTING.md
  DEVELOPING.md
  README.md
  docs/developing.md
  docs/releasing.md
Labels: documentation

#125 fix: set state on mounted component only
  src/components/Wallet.jsx
  src/components/Wallets.jsx
Labels: bug

#126 refactor: dry up app layout
  src/components/App.jsx
  src/components/CreateWallet.jsx
  src/components/CurrentWalletAdvanced.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/Earn.jsx
  src/components/Layout.jsx
  src/components/Receive.jsx
  src/components/Send.jsx
  src/components/Settings.jsx
  src/components/Wallets.jsx
Labels: tech dept

#122 feat: readd websocket connection
  docker/regtest/docker-compose.yml
  docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
  src/components/App.jsx
  src/components/Earn.jsx
  src/components/Send.jsx
  src/context/WebsocketContext.jsx
  src/index.jsx
  src/setupProxy.js
Labels: enhancement
