Repository joinmarket-webui/jam, pull requests merged in 2022-04, with the labels that each got.

#198 Remove skip button quiz screen
  src/components/App.jsx
  src/components/CreateWallet.css
  src/components/CreateWallet.jsx
  src/components/CreateWallet.test.jsx
  src/components/Seedphrase.css
  src/components/Seedphrase.jsx
  src/index.css
Labels: UI/UX, security

#197 dev: enable npm config `engine-strict`
  .github/workflows/build.yml
  .npmrc
  package.json
Labels: devtools

#199 fix: do not hide CreateWallet component on connection errors
  src/components/App.jsx
  src/components/CreateWallet.jsx
  src/components/DisplayUTXOs.jsx
  src/components/Earn.jsx
  src/components/Send.jsx
  src/components/Wallet.jsx
  src/context/ServiceInfoContext.tsx
  src/context/WalletContext.tsx
  src/libs/JmWalletApi.ts
Labels: bug, UI/UX

#200 fix: force-close pending websockets connections
  src/context/WebsocketContext.jsx
Labels: bug

#215 refactor: Add route constants
  src/components/App.jsx
  src/components/CreateWallet.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/DisplayAccounts.jsx
  src/components/Navbar.jsx
  src/components/Wallet.jsx
  src/components/Wallets.jsx
  src/constants/routes.ts
Labels: enhancement

#213 refactor: reload wallet info
  src/components/App.jsx
  src/components/CurrentWalletAdvanced.tsx
  src/components/CurrentWalletMagic.jsx
  src/components/Navbar.jsx
  src/components/Send.jsx
  src/context/ServiceInfoContext.tsx
  src/context/WalletContext.tsx
  src/libs/JmWalletApi.ts
Labels: tech dept

#211 feat: add cheatsheet
  public/sprite.svg
  src/components/App.jsx
  src/components/Cheatsheet.tsx
  src/components/CreateWallet.jsx
  src/components/CreateWallet.test.jsx
  src/components/Navbar.jsx
  src/constants/featureFlags.ts
  src/context/SettingsContext.jsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: enhancement, concept

#219 fix: use `1000` as websocket close code
  src/context/WebsocketContext.jsx
Labels: bug

#222 ui: small visual adaptions after placeholder PR
  public/sprite.svg
  src/components/Balance.jsx
  src/components/Balance.test.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/CurrentWalletMagic.module.css
  src/components/Navbar.jsx
  src/components/Receive.jsx
  src/components/Receive.module.css
  src/components/Send.css
  src/components/Send.jsx
Labels: UI/UX

#218 fix: prevent operations when maker/taker service is running
  public/sprite.svg
  src/components/DisplayUTXOs.jsx
  src/components/Send.css
  src/components/Send.jsx
  src/components/ToggleSwitch.jsx
  src/components/ToggleSwitch.module.css
  src/context/ServiceInfoContext.tsx
  src/context/WalletContext.tsx
  src/i18n/locales/fr/translation.json
  src/index.css
Labels: enhancement

#229 chore: update dependencies
  package-lock.json
  package.json
  src/components/Onboarding.jsx
Labels: dependencies

#223 feat: reset wallet when token became invalid
  src/context/ServiceInfoContext.tsx
  src/libs/JmWalletApi.ts
Labels: enhancement

#231 reload session info on Earn and Wallets screen
  src/components/App.test.jsx
  src/components/CreateWallet.test.jsx
  src/components/Earn.jsx
  src/components/Earn.module.css
  src/components/Wallet.test.jsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
Labels: UI/UX

#234 refactor: use Formik on Earn screen
  src/components/Earn.jsx
Labels: tech dept
