Repository joinmarket-webui/jam, pull requests merged in 2022-05, with the labels that each got.

#230 217 issue unify css
  src/components/CreateWallet.jsx
  src/components/CreateWallet.module.css
  src/components/Seedphrase.jsx
  src/components/Seedphrase.module.css
  src/components/Send.css
  src/components/Send.jsx
  src/components/Send.module.css
Labels: UI/UX, tech dept

#232 refactor: reusable copy-to-clipboard mechanism
  src/components/CopyButton.tsx
  src/components/Receive.jsx
  src/utils.js
  src/utils.ts
Labels: tech dept

#236 Reload wallet data after send
  src/components/Send.jsx
Labels: enhancement

#235 Formik validation in Wallet component
  src/components/App.jsx
  src/components/CreateWallet.jsx
  src/components/Earn.jsx
  src/components/Wallet.jsx
  src/components/Wallet.test.jsx
  src/utils.ts
Labels: tech dept

#238 refactor: Report overlay
  src/components/Earn.jsx
  src/components/EarnReport.module.css
  src/components/EarnReport.tsx
  src/i18n/locales/en/translation.json
Labels: enhancement, UI/UX

#243 ui: prevent password unlock input from resizing on error
  src/components/Wallet.jsx
  src/components/Wallet.module.css
Labels: UI/UX

#242 feat: scheduled transactions prototype
  docker/regtest/init-setup.sh
  package.json
  src/components/App.jsx
  src/components/Jam.jsx
  src/components/Jam.module.css
  src/components/Navbar.jsx
  src/components/ToggleSwitch.jsx
  src/components/ToggleSwitch.module.css
  src/constants/featureFlags.ts
  src/constants/routes.ts
  src/context/WalletContext.tsx
  src/i18n/locales/en/translation.json
  src/libs/JmWalletApi.ts
Labels: enhancement, concept

#260 fix: prevent starting/stopping scheduler while data is loading
  src/components/Jam.jsx
Labels: bug

#265 fix: possible reference error in catch clause
  src/components/Jam.jsx
Labels: bug

#240 refactor: remove catch all style rule for border-color in dark mode
  src/components/Send.module.css
  src/index.css
Labels: tech dept

#264 fix: delay scheduler start/stop
  src/components/Jam.jsx
  src/libs/JmWalletApi.ts
Labels: bug, tech dept, scheduled transactions

#247 feat: Individual balance toggle
  src/components/Balance.jsx
  src/components/Balance.test.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/Navbar.jsx
Labels: enhancement, UI/UX

#239 ui: decrease brightness of placeholder in light theme
  src/index.css
Labels: UI/UX

#270 ui: big red button for payments without improved privacy
  src/components/Send.jsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#272 feat: prevent address reuse on Jam screen
  src/components/Jam.jsx
  src/i18n/locales/en/translation.json
Labels: enhancement, UI/UX

#280 feat: add tagline to splash & improve intro copy
  src/i18n/locales/en/translation.json
Labels: UI/UX

#281 feat(footer): show Jam version
  src/components/App.jsx
Labels: UI/UX

#263 fix: prevent starting scheduler when utxo preconditions are not met
  src/components/DisplayUTXOs.jsx
  src/components/Jam.jsx
  src/i18n/locales/en/translation.json
Labels: enhancement, WIP

#288 chore: enable cheatsheet
  src/components/App.jsx
  src/components/Cheatsheet.tsx
  src/constants/features.ts
  src/i18n/locales/en/translation.json
Labels: enhancement, UI/UX

#274 fix: handle new "total_balance" format
  src/components/CurrentWalletMagic.jsx
  src/components/DisplayAccounts.jsx
  src/components/Jam.jsx
  src/components/Navbar.jsx
  src/components/Send.jsx
  src/context/WalletContext.tsx
  src/hooks/BalanceSummary.test.tsx
  src/hooks/BalanceSummary.ts
  src/i18n/testConfig.ts
  src/testUtils.tsx
Labels: bug, UI/UX, WIP

#276 feat: add sat conversion to send screen privacy levels based on settings
  src/components/Balance.jsx
  src/components/Send.jsx
  src/utils.ts
Labels: enhancement, UI/UX
