Repository joinmarket-webui/jam, pull requests merged in 2022-03, with the labels that each got.

#143 docs: update raspiblitz install instructions
  README.md
Labels: documentation

#144 docs: update integrations in readme
  README.md
  docs/assets/citadel.png
  docs/assets/raspiblitz-dark.svg
  docs/assets/raspiblitz-light.svg
  docs/assets/umbrel.svg
Labels: documentation

#130 test: add basic test suite
  .github/workflows/build.yml
  package-lock.json
  package.json
  src/__util__/AllTheProviders.jsx
  src/components/App.test.jsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
  src/context/WebsocketContext.jsx
  src/setupTests.js
Labels: devtools

#131 Rename to Jam
  CONTRIBUTING.md
  README.md
  docs/assets/readme-header-dark.svg
  docs/assets/readme-header-light.svg
  docs/assets/screenshot-dark.png
  docs/assets/screenshot-light.png
  docs/developing.md
  package-lock.json
  package.json
  public/index.html
  readme-header.svg
  src/components/App.jsx
  src/components/Navbar.jsx
  src/components/Onboarding.jsx
Labels: documentation

#147 chore: check for dependencies in dev setup scripts
  docker/regtest/common.sh
  docker/regtest/dockerfile-deps/joinmarket/latest/docker-entrypoint.sh
  docker/regtest/fund-wallet.sh
  docker/regtest/init-setup.sh
  docker/regtest/mine-block.sh
Labels: enhancement, devtools

#146 fix: use own qrcode component to display addresses
  package-lock.json
  package.json
  src/components/BitcoinQR.jsx
  src/components/Receive.jsx
  src/index.css
  src/index.jsx
Labels: bug, enhancement

#150 fix: update suggested number of collaborators
  src/components/Send.jsx
Labels: bug

#153 feat: i18n
  .tx/transifex.yml
  package-lock.json
  package.json
  public/sprite.svg
  src/__util__/AllTheProviders.jsx
  src/components/App.test.jsx
  src/components/Settings.jsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
  src/i18n/README.md
  src/i18n/config.js
  src/i18n/languages.js
  src/i18n/locales/en/translation.json
  src/i18n/testConfig.js
  src/index.jsx
  src/testUtils.jsx
Labels: enhancement

#162 Fix page reloads
  src/components/App.jsx
  src/components/CurrentWalletAdvanced.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/Receive.jsx
  src/components/Send.jsx
  src/context/WalletContext.jsx
Labels: bug

#165 fix: receive address copy button not working
  src/components/Receive.jsx
Labels: bug

#166 ui: display message if utxos are empty
  src/components/CurrentWalletAdvanced.jsx
Labels: UI/UX

#160 feat: add display seed phrase option to settings
  public/sprite.svg
  src/components/CreateWallet.jsx
  src/components/Seedphrase.jsx
  src/components/Settings.jsx
  src/index.css
  src/libs/JmWalletApi.js
Labels: enhancement

#170 chore(release): prepare v0.0.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#171 feat: satscomma formatting for bitcoin balances
  src/components/Balance.jsx
  src/components/Balance.test.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/DisplayAccounts.jsx
  src/components/DisplayUTXOs.jsx
  src/components/Navbar.jsx
  src/index.css
Labels: enhancement, UI/UX

#174 feat: translate screens
  src/components/App.jsx
  src/components/App.test.jsx
  src/components/CreateWallet.jsx
  src/components/CurrentWalletAdvanced.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/DisplayAccountUTXOs.jsx
  src/components/DisplayAccounts.jsx
  src/components/DisplayUTXOs.jsx
  src/components/Earn.jsx
  src/components/Navbar.jsx
  src/components/Onboarding.jsx
  src/components/Receive.jsx
  src/components/Send.jsx
  src/components/Settings.jsx
  src/components/Settings.test.jsx
  src/components/Wallet.jsx
  src/components/Wallet.test.jsx
  src/i18n/locales/en/translation.json
  src/utils.js
Labels: enhancement

#178 Update regtest env
  docker/regtest/docker-compose.yml
  docker/regtest/readme.md
  package.json
Labels: devtools

#156 feat: add seed phrase backup confirmation during wallet creation
  package-lock.json
  src/components/CreateWallet.jsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: enhancement

#176 Add typescript support
  package-lock.json
  package.json
  src/components/App.jsx
  src/components/CreateWallet.jsx
  src/components/CurrentWalletAdvanced.test.tsx
  src/components/CurrentWalletAdvanced.tsx
  src/components/Receive.jsx
  src/index.tsx
  src/libs/JmWalletApi.js
  src/libs/JmWalletApi.ts
  src/reportWebVitals.js
  src/reportWebVitals.ts
  src/session.js
  src/session.ts
  tsconfig.json
Labels: devtools

#180 fix: pass correct request body in send-direct request
  src/components/DisplayUTXOs.jsx
  src/components/Send.jsx
Labels: bug

#185 fix: pass glob pattern to prettier in single quotes
  package.json
Labels: devtools

#175 Improve lock/unlock mechanism
  src/components/ActivityIndicators.jsx
  src/components/App.jsx
  src/components/App.test.jsx
  src/components/CreateWallet.jsx
  src/components/CurrentWalletMagic.jsx
  src/components/Earn.jsx
  src/components/Navbar.jsx
  src/components/Receive.jsx
  src/components/Send.jsx
  src/components/Settings.jsx
  src/components/Settings.test.jsx
  src/components/Wallet.jsx
  src/components/Wallet.test.jsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
  src/context/ServiceInfoContext.tsx
  src/i18n/locales/en/translation.json
  src/index.css
  src/index.tsx
  src/libs/JmWalletApi.ts
  src/testUtils.jsx
Labels: UI/UX

#184 feat: sweep mixdepths
  public/sprite.svg
  src/components/Send.css
  src/components/Send.jsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: enhancement

#195 chore(release): prepare v0.0.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
