Repository joinmarket-webui/jam, pull requests merged in 2022-09, with the labels that each got.

#478 feat: ability to retrieve logs
  docker/regtest/dockerfile-deps/joinmarket/directory_node/docker-entrypoint.sh
  docker/regtest/dockerfile-deps/joinmarket/directory_node/supervisor-conf/directory-node.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/jam-entrypoint.sh
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/jmwalletd.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/ob-watcher.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/supervisord.conf
  docker/regtest/dockerfile-deps/joinmarket/latest/supervisor-conf/tor.conf
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/Dockerfile
  package.json
  src/components/LogOverlay.module.css
  src/components/LogOverlay.tsx
  src/components/Settings.jsx
  src/i18n/locales/en/translation.json
  src/libs/JamApi.ts
  src/libs/JmWalletApi.ts
  src/setupProxy.js
Labels: enhancement, concept

#492 fix: redirect to home if no wallet is active on route `/wallet`
  src/components/App.jsx
  src/components/Wallet.jsx
Labels: bug

#495 ui: improve layout of JarDetailsOverlay on small screens
  src/components/TablePagination.tsx
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
Labels: UI/UX

#494 fix: reload wallet info after stopping scheduler manually
  src/components/Jam.jsx
Labels: bug

#493 ui: use 'zoom-in' cursor when hovering over jars on main page
  src/components/jars/Jar.module.css
Labels: enhancement, UI/UX

#491 chore(i18n): add missing translations for fidelity bonds form
  src/components/fb/CreateFidelityBond.jsx
  src/i18n/locales/en/translation.json
Labels: bug, Fidelity Bonds

#485 fix: precondition for collaborative transactions
  docker/regtest/docker-compose.yml
  src/components/CoinjoinPreconditionViolationAlert.tsx
  src/components/Jam.jsx
  src/components/Send.jsx
  src/hooks/CoinjoinPrecondition.test.tsx
  src/hooks/CoinjoinPrecondition.ts
  src/hooks/CoinjoinRequirements.test.ts
  src/hooks/CoinjoinRequirements.ts
  src/i18n/locales/en/translation.json
  src/utils.test.ts
  src/utils.ts
Labels: bug

#497 feat: abort collaborative transaction
  src/components/Jam.jsx
  src/components/Send.jsx
  src/i18n/locales/en/translation.json
  src/libs/JmWalletApi.ts
Labels: enhancement, UI/UX

#498 fix: do not disable submit button on warnings on Send page
  src/components/Send.jsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: concept, UI/UX

#501 fix: consistent button text during screen initialization
  src/components/Send.jsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#500 chore(release): prepare v0.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#507 fix(navbar): send before earn
  src/components/Navbar.jsx
Labels: bug, UI/UX

#505 build: update dependencies
  package-lock.json
  package.json
Labels: dependencies

#506 build(deps): remove web-vitals
  package-lock.json
  package.json
  src/index.tsx
  src/reportWebVitals.ts
Labels: dependencies

#512 docs(readme): update screenshots & text
  README.md
  docs/assets/readme-header-dark.svg
  docs/assets/readme-header-light.svg
  docs/assets/screenshot-dark.png
  docs/assets/screenshot-light.png
Labels: documentation

#513 chore: update readme and package.json
  CONTRIBUTING.md
  README.md
  docs/developing.md
  package.json
  src/i18n/README.md
Labels: documentation

#509 refactor: components from jsx to tsx
  src/components/ActivityIndicators.jsx
  src/components/ActivityIndicators.tsx
  src/components/Alert.jsx
  src/components/Alert.tsx
  src/components/App.test.tsx
  src/components/App.tsx
  src/components/JarSelectorModal.tsx
  src/components/Layout.tsx
  src/components/Send.jsx
  src/components/Wallets.jsx
  src/components/fb/CreateFidelityBond.jsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jars/Jar.tsx
  src/index.tsx
  src/setupTests.ts
  typings.d.ts
Labels: refactoring

#510 feat(send): show txid on successful direct-send
  src/components/Send.jsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
  src/index.css
Labels: enhancement

#514 feat: show sum of selected utxos
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jar_details/UtxoDetailModule.module.css
  src/components/jar_details/UtxoDetailModule.tsx
  src/components/jar_details/UtxoList.tsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#519 deps: update `react-router-dom` from v6.3.0 to v6.4.1
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/CreateWallet.test.jsx
  src/components/MainWalletView.jsx
  src/components/Receive.jsx
  src/components/Settings.test.jsx
  src/components/Wallet.test.jsx
  src/components/Wallets.test.jsx
  src/index.tsx
  src/testUtils.tsx
Labels: dependencies
