Repository joinmarket-webui/jam, pull requests merged in 2022-12, with the labels that each got.

#573 Settings subsections refined w/ translation addition
  src/components/Settings.jsx
  src/components/Settings.test.jsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: enhancement

#566 refactor: speed up initial page load
  src/components/Earn.jsx
  src/components/Jam.jsx
  src/components/JarSelectorModal.tsx
  src/components/Jars.tsx
  src/components/MainWalletView.module.css
  src/components/MainWalletView.tsx
  src/components/Send.jsx
  src/components/fb/CreateFidelityBond.jsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/context/WalletContext.tsx
Labels: performance, refactoring

#572 fix: no. of collaborators as integer
  src/components/Send.jsx
  src/components/Send.module.css
Labels: bug

#556 feat: spend fidelity bond
  public/sprite.svg
  src/components/Balance.jsx
  src/components/Balance.test.jsx
  src/components/Earn.jsx
  src/components/Jam.jsx
  src/components/Modal.tsx
  src/components/PaymentConfirmModal.module.css
  src/components/PaymentConfirmModal.tsx
  src/components/Send.jsx
  src/components/Send.module.css
  src/components/fb/CreateFidelityBond.jsx
  src/components/fb/ExistingFidelityBond.module.css
  src/components/fb/ExistingFidelityBond.tsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/fb/SpendFidelityBondModal.module.css
  src/components/fb/SpendFidelityBondModal.tsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jar_details/UtxoList.module.css
  src/components/jar_details/UtxoList.tsx
  src/context/WalletContext.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
  src/libs/JamApi.ts
  src/libs/JmWalletApi.ts
Labels: enhancement, concept

#575 chore(release): v0.1.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#551 feat: Show jar total amount in detail view
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
  src/i18n/locales/en/translation.json
Labels: enhancement, UI/UX

#578 Add MyNode to Installation Section
  README.md
  docs/assets/mynode.png
Labels: documentation
