Repository joinmarket-webui/jam, pull requests merged in 2023-02, with the labels that each got.

#584 fix: correctly render existing bonds in Safari
  src/components/fb/CreateFidelityBond.jsx
  src/components/fb/ExistingFidelityBond.tsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/fb/utils.ts
  src/context/WalletContext.tsx
Labels: bug

#585 fix: install python3-venv in regtest environment
  docker/regtest/dockerfile-deps/joinmarket/directory_node/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/directory_node/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/latest/Dockerfile
  docker/regtest/dockerfile-deps/joinmarket/latest/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/default.cfg
Labels: devtools

#601 fix(fb): correctly display success screen after unlocking fb
  src/components/Earn.jsx
  src/components/fb/SpendFidelityBondModal.tsx
Labels: bug

#605 build(deps): update bootstrap to v5.2.3
  package-lock.json
  package.json
Labels: dependencies

#603 fix(fees): allow input for relative fee limit of 0.0001%
  src/components/settings/FeeConfigModal.tsx
Labels: bug

#604 fix(fees): allow min tx fee of 1sat/vbyte
  src/components/settings/FeeConfigModal.tsx
Labels: enhancement, blocked

#591 feat: quick freeze/unfreeze utxos
  public/sprite.svg
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jar_details/UtxoDetailModal.module.css
  src/components/jar_details/UtxoDetailModal.tsx
  src/components/jar_details/UtxoList.module.css
  src/components/jar_details/UtxoList.tsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: enhancement, UI/UX

#600 ui(Send): replace dropdown input with JarSelector
  src/components/Accordion.tsx
  src/components/Earn.jsx
  src/components/Receive.jsx
  src/components/Send/Send.module.css
  src/components/Send/index.tsx
  src/components/jars/Jar.module.css
  src/context/BalanceSummary.ts
Labels: UI/UX

#599 feat(Jam): add success message
  docker/regtest/readme.md
  package.json
  src/components/Alert.tsx
  src/components/EarnReport.tsx
  src/components/Jam.jsx
  src/components/Jam.tsx
  src/components/LogOverlay.tsx
  src/components/MainWalletView.tsx
  src/components/Orderbook.tsx
  src/components/PageTitle.tsx
  src/components/fb/SpendFidelityBondModal.tsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/context/ServiceInfoContext.tsx
  src/globals.d.ts
  src/i18n/locales/en/translation.json
  src/libs/JmWalletApi.ts
Labels: enhancement, UI/UX

#609 chore(release): v0.1.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
