Repository joinmarket-webui/jam, pull requests merged in 2023-01, with the labels that each got.

#583 add start9 logo and link to readme
  README.md
  docs/assets/start9.png
Labels: documentation

#590 Add RaspiBolt to Installation section
  README.md
  docs/assets/raspibolt.png
Labels: documentation

#588 ISSUE-528: improve JarDetailsOverlay header
  src/components/SegmentedTabs.tsx
  src/components/jar_details/JarDetailsOverlay.module.css
  src/components/jar_details/JarDetailsOverlay.tsx
Labels: UI/UX

#593 ui(Jars): move jar info next to icon on small screens
  src/components/Jars.module.css
  src/components/jars/Jar.module.css
  src/components/jars/Jar.tsx
Labels: UI/UX

#592 ui(Wallet): add lock/unlock icon
  src/components/Wallet.module.css
  src/components/Wallet.test.tsx
  src/components/Wallet.tsx
  src/components/Wallets.jsx
  src/index.css
Labels: UI/UX

#594 refactor(Balance): jsx to tsx
  src/components/Balance.module.css
  src/components/Balance.test.tsx
  src/components/Balance.tsx
  src/components/Navbar.module.css
  src/components/Navbar.tsx
  src/components/fb/FidelityBondSteps.module.css
Labels: refactoring

#595 Send: Hide "number of collaborators" behind send options
  src/components/Accordion.tsx
  src/components/Earn.jsx
  src/components/Earn.module.css
  src/components/Orderbook.tsx
  src/components/Receive.jsx
  src/components/Receive.module.css
  src/components/Send/CollaboratorsSelector.tsx
  src/components/Send/index.tsx
  src/components/fb/SpendFidelityBondModal.tsx
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
Labels: UI/UX

#587 refactor(send): follow-up PR to #582
  src/components/Send/CollaboratorsSelector.module.css
  src/components/Send/CollaboratorsSelector.tsx
  src/components/Send/Send.module.css
  src/components/Send/index.tsx
Labels: refactoring

#586 feat: add dedicated error page
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/ErrorPage.tsx
  src/components/PageTitle.tsx
  src/constants/debugFeatures.ts
  src/constants/routes.ts
  src/i18n/locales/en/translation.json
Labels: enhancement
