Repository joinmarket-webui/jam, pull requests merged in 2023-09, with the labels that each got.

#656 fix(ui): consistent button styles
  src/components/App.tsx
  src/components/CopyButton.tsx
  src/components/CreateWallet.jsx
  src/components/Earn.jsx
  src/components/Earn.module.css
  src/components/ImportWallet.tsx
  src/components/Jam.module.css
  src/components/Jam.tsx
  src/components/MainWalletView.module.css
  src/components/MnemonicWordInput.module.css
  src/components/MnemonicWordInput.tsx
  src/components/Navbar.tsx
  src/components/Onboarding.jsx
  src/components/Onboarding.module.css
  src/components/Receive.jsx
  src/components/Receive.module.css
  src/components/Send/Send.module.css
  src/components/Send/index.tsx
  src/components/WalletCreationConfirmation.tsx
  src/components/WalletCreationForm.module.css
  src/components/WalletCreationForm.tsx
  src/components/fb/CreateFidelityBond.module.css
  src/components/fb/CreateFidelityBond.tsx
  src/components/fb/ExistingFidelityBond.tsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/jar_details/DisplayBranch.tsx
  src/constants/debugFeatures.ts
  src/i18n/locales/en/translation.json
  src/index.css
Labels: UI/UX

#647 feat: backend version based feature toggles
  .gitignore
  src/components/App.test.tsx
  src/components/CreateWallet.test.jsx
  src/components/Settings.jsx
  src/components/Wallet.test.tsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
  src/constants/features.ts
  src/context/ServiceInfoContext.tsx
  src/globals.d.ts
  src/libs/JmWalletApi.ts
Labels: enhancement

#657 chore: apply new formatting rules after prettier upgrade
  package-lock.json
  package.json
  src/components/App.tsx
  src/components/CoinjoinPreconditionViolationAlert.tsx
  src/components/CopyButton.tsx
  src/components/CreateWallet.jsx
  src/components/CreateWallet.test.jsx
  src/components/EarnReport.tsx
  src/components/ImportWallet.tsx
  src/components/Jam.tsx
  src/components/LogOverlay.tsx
  src/components/Navbar.tsx
  src/components/Onboarding.jsx
  src/components/Orderbook.tsx
  src/components/PreventLeavingPageByMistake.tsx
  src/components/Receive.jsx
  src/components/RescanChain.tsx
  src/components/ScheduleProgress.jsx
  src/components/Send/FeeBreakdown.tsx
  src/components/Send/helpers.ts
  src/components/Send/index.tsx
  src/components/Settings.jsx
  src/components/Settings.test.jsx
  src/components/Wallet.test.tsx
  src/components/Wallet.tsx
  src/components/WalletCreationForm.tsx
  src/components/Wallets.jsx
  src/components/Wallets.test.jsx
  src/components/fb/CreateFidelityBond.tsx
  src/components/fb/LockdateForm.tsx
  src/components/fb/SpendFidelityBondModal.tsx
  src/components/fb/utils.test.ts
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/jar_details/UtxoList.tsx
  src/components/settings/FeeConfigModal.tsx
  src/context/BalanceSummary.test.tsx
  src/context/BalanceSummary.ts
  src/context/ServiceConfigContext.tsx
  src/context/ServiceInfoContext.tsx
  src/context/SettingsContext.tsx
  src/context/WalletContext.tsx
  src/context/WebsocketContext.jsx
  src/hooks/CoinjoinRequirements.ts
  src/hooks/Fees.ts
  src/index.css
  src/index.tsx
  src/libs/JmObwatchApi.ts
  src/libs/JmWalletApi.ts
  src/setupProxy.js
  src/setupTests.ts
Labels: dependencies, refactoring

#658 chore(import): display warning on large gaplimit values
  src/components/Accordion.tsx
  src/components/ImportWallet.tsx
  src/i18n/locales/en/translation.json
Labels: UI/UX

#660 feat(i18n): update to Chinese translations
  src/i18n/locales/zh_Hans/translation.json
  src/i18n/locales/zh_Hant/translation.json
Labels: i18n

#666 chore(release): v0.1.6
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#668 feat: display ui/backend version
  src/components/Footer.tsx
  src/context/ServiceInfoContext.tsx
  src/utils.test.ts
  src/utils.ts
  tsconfig.json
Labels: enhancement
