Repository joinmarket-webui/jam, pull requests merged in 2024-10, with the labels that each got.

#855 chore(release): v0.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#866 build: update node version
  .github/workflows/build.yml
  .nvmrc
  package.json
Labels: dependencies, devtools

#867 chore(i18n): update splashscreen_warning_text: improve english
  src/i18n/locales/en/translation.json
Labels: i18n

#862 fix: relative fee greater than zero
  src/components/Earn.tsx
  src/components/ImportWallet.tsx
  src/components/Orderbook.tsx
  src/components/Send/index.tsx
  src/components/settings/FeeConfigModal.tsx
  src/constants/jam.ts
  src/constants/jm.ts
  src/context/ServiceInfoContext.tsx
  src/context/WalletContext.tsx
  src/hooks/CoinjoinRequirements.ts
  src/hooks/Fees.ts
  src/utils.test.ts
  src/utils.ts
Labels: bug

#863 build(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies
