Repository joinmarket-webui/jam, pull requests merged in 2024-08, with the labels that each got.

#806 feat: unit and visibility toggle on main wallet view
  src/components/MainWalletView.tsx
Labels: UI/UX

#802 follow-up(PR771): quick freeze/unfreeze
  public/sprite.svg
  src/components/Balance.module.css
  src/components/Balance.tsx
  src/components/Divider.module.css
  src/components/Divider.tsx
  src/components/JarSelectorModal.tsx
  src/components/MainWalletView.module.css
  src/components/MainWalletView.tsx
  src/components/Modal.module.css
  src/components/Modal.tsx
  src/components/Send/AmountInputField.tsx
  src/components/Send/SendForm.tsx
  src/components/Send/ShowUtxos.module.css
  src/components/Send/ShowUtxos.tsx
  src/components/Send/SourceJarSelector.tsx
  src/components/jar_details/UtxoList.tsx
  src/components/settings/FeeConfigModal.module.css
  src/components/settings/FeeConfigModal.tsx
  src/context/WalletContext.tsx
  src/i18n/locales/en/translation.json
Labels: refactoring

#817 Update SchedulerConfirmationModal.tsx
  src/components/SchedulerConfirmationModal.tsx
Labels: refactoring

#813 build(deps): update dependencies
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/BitcoinAmountInput.tsx
  src/components/Send/SendForm.tsx
Labels: dependencies

#825 (ui) Static Cooking Pot
  public/sprite.svg
  src/components/ScheduleProgress.tsx
Labels: UI/UX

#821 Refactor and DRYer code
  src/components/Jam.tsx
  src/components/Modal.tsx
  src/components/SchedulerConfirmationModal.module.css
  src/components/SchedulerConfirmationModal.tsx
  src/i18n/locales/en/translation.json
Labels: refactoring

#820 fix: default for collaborators set to 1 and added dev tag
  src/components/Send/CollaboratorsSelector.tsx
  src/components/Send/helpers.ts
  src/components/Send/index.tsx
Labels: devtools
