Repository joinmarket-webui/jam, pull requests merged in 2024-02, with the labels that each got.

#678 feat: renew fidelity bond
  src/components/Earn.tsx
  src/components/PaymentConfirmModal.tsx
  src/components/Send/index.tsx
  src/components/fb/CreateFidelityBond.tsx
  src/components/fb/FidelityBondSteps.tsx
  src/components/fb/LockdateForm.tsx
  src/components/fb/SpendFidelityBondModal.tsx
  src/hooks/WaitForUtxosToBeSpent.ts
  src/i18n/locales/en/translation.json
  src/index.css
Labels: enhancement, Fidelity Bonds

#720 636 check for existing wallet
  src/components/CreateWallet.test.tsx
  src/components/WalletCreationForm.tsx
  src/i18n/locales/en/translation.json
Labels: bug

#722 chore(release): v0.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
