Repository joinmarket-webui/jam, pull requests merged in 2024-01, with the labels that each got.

#715 build(deps): update dependencies
  package-lock.json
  package.json
  src/components/EarnReport.tsx
  src/components/Orderbook.tsx
  src/components/jar_details/UtxoList.tsx
Labels: dependencies

#711 feat: align amount input fields
  src/components/BitcoinAmountInput.test.tsx
  src/components/BitcoinAmountInput.tsx
  src/components/Earn.module.css
  src/components/Earn.tsx
  src/components/Receive.module.css
  src/components/Receive.tsx
  src/components/Send/AmountInputField.module.css
  src/components/Send/AmountInputField.tsx
  src/components/Send/SendForm.tsx
  src/components/settings/FeeConfigModal.module.css
  src/components/settings/FeeConfigModal.tsx
  src/i18n/locales/en/translation.json
  src/utils.test.ts
  src/utils.ts
Labels: enhancement, UI/UX

#718 automatically jump to the next input box when confirming the seed phr…
  src/components/MnemonicPhraseInput.tsx
  src/components/MnemonicWordInput.tsx
Labels: enhancement, UI/UX

#706 feat: custom tx fee on direct and collaborative send
  src/components/Earn.tsx
  src/components/PaymentConfirmModal.tsx
  src/components/SegmentedTabs.module.css
  src/components/SegmentedTabs.tsx
  src/components/Send/AmountInputField.module.css
  src/components/Send/AmountInputField.tsx
  src/components/Send/DestinationInputField.module.css
  src/components/Send/DestinationInputField.tsx
  src/components/Send/SendForm.module.css
  src/components/Send/SendForm.tsx
  src/components/Send/index.tsx
  src/components/jar_details/JarDetailsOverlay.tsx
  src/components/settings/TxFeeInputField.tsx
  src/constants/features.ts
  src/hooks/Fees.ts
  src/i18n/locales/en/translation.json
  src/libs/JmWalletApi.ts
Labels: enhancement
