Repository joinmarket-webui/jam, pull requests merged in 2024-09, with the labels that each got.

#829 Update languages.ts to replace incorrect descriptions for Chinese translations
  src/i18n/languages.ts
Labels: i18n

#832 chore(i18n): remove unused translations
  .github/workflows/build.yml
  src/components/App.tsx
  src/components/Settings.test.tsx
  src/i18n/locales/de/translation.json
  src/i18n/locales/en/translation.json
  src/i18n/locales/fr/translation.json
  src/i18n/locales/it/translation.json
  src/i18n/locales/pt_BR/translation.json
  src/i18n/locales/zh_Hans/translation.json
  src/i18n/locales/zh_Hant/translation.json
Labels: i18n

#834 add matrix to footer
  src/components/Footer.tsx
Labels: enhancement

#838 Added rescan page translations and removed dev mode tag
  src/components/RescanChain.tsx
  src/components/Settings.tsx
  src/i18n/locales/en/translation.json
Labels: enhancement

#840 dev: use `npm run dev` to run app in dev mode
  CONTRIBUTING.md
  docker/regtest/readme.md
  docs/developing.md
  package.json
  src/components/LogOverlay.tsx
Labels: devtools

#845 build(deps): update dependencies
  package-lock.json
  package.json
  src/context/ServiceInfoContext.tsx
  src/context/WalletContext.tsx
  src/utils.ts
Labels: dependencies

#848 fix(main): properly fade out jar tooltips
  src/components/jars/Jar.tsx
Labels: bug, UI/UX

#849 ui: new joining indicator symbol
  public/sprite.svg
  src/components/ActivityIndicators.tsx
  src/components/Navbar.tsx
  src/components/Send/index.tsx
  src/components/Wallet.tsx
  src/index.css
Labels: concept, UI/UX

#846 perf: optimize api request
  src/components/App.tsx
  src/components/Earn.tsx
  src/context/WalletContext.tsx
  src/index.tsx
Labels: performance

#853 Fix months order across timezones
  src/components/fb/LockdateForm.test.tsx
  src/components/fb/LockdateForm.tsx
Labels: bug

#847 chore: small quick freeze modal adaptions
  src/components/PaymentConfirmModal.tsx
  src/components/Send/ShowUtxos.tsx
  src/components/Send/SourceJarSelector.tsx
  src/components/Send/index.tsx
  src/components/utxo/Confirmations.module.css
  src/i18n/locales/en/translation.json
Labels: UI/UX
