Repository joinmarket-webui/jam, pull requests merged in 2025-06, with the labels that each got.

#903 build(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies

#906 feat: orderbook hard refresh
  src/components/Orderbook.tsx
  src/i18n/locales/en/translation.json
  src/index.css
Labels: enhancement, concept, UI/UX

#926 Feat: cleaned up layout and use listutxos
  src/components/DisplayLogo.tsx
  src/components/JamLanding.tsx
  src/components/layout/Layout.tsx
  src/components/layout/display-mode-context.ts
  src/hooks/useDisplayMode.ts
  src/hooks/useWalletDisplay/index.ts
Labels: v2

#929 chore(prettier): add prettierrc file and import sorting
  .prettierignore
  .prettierrc.json
  .storybook/preview.ts
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/components/CreateWallet.tsx
  src/components/Footer.tsx
  src/components/JamLanding.tsx
  src/components/Login.tsx
  src/components/Navbar.tsx
  src/components/layout/Layout.tsx
  src/components/ui/alert.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/select.tsx
  src/components/ui/separator.tsx
  src/components/ui/tooltip.tsx
  src/hooks/useWalletDisplay/index.ts
  src/lib/config.ts
  src/lib/jm-api/generated/client/@tanstack/react-query.gen.ts
  src/lib/jm-api/generated/client/client.gen.ts
  src/lib/jm-api/generated/client/index.ts
  src/lib/jm-api/generated/client/sdk.gen.ts
  src/lib/jm-api/generated/client/types.gen.ts
  src/lib/jm-api/index.ts
  src/lib/session.ts
  src/lib/utils.ts
  src/main.tsx
  src/stories/Alert.stories.tsx
  src/stories/Avatar.stories.tsx
  src/stories/Badge.stories.tsx
  src/stories/Button.stories.tsx
  src/stories/Card.stories.tsx
  src/stories/Footer.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/Jar.stories.tsx
  src/stories/Label.stories.tsx
  src/stories/Navbar.stories.tsx
  src/stories/Navigation.stories.tsx
  src/stories/Select.stories.tsx
  src/stories/Separator.stories.tsx
  src/stories/Sonner.stories.tsx
  src/stories/ThemeToggle.stories.tsx
  src/stories/Tooltip.stories.tsx
  vite.config.ts
Labels: v2

#930 chore(v2): add favicon
  index.html
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon.ico
  public/favicon.svg
  public/mstile-144x144.png
  public/mstile-150x150.png
  public/mstile-310x150.png
  public/mstile-310x310.png
  public/mstile-70x70.png
  public/robots.txt
  public/safari-pinned-tab.svg
  public/site.webmanifest
  public/vite.svg
Labels: enhancement, UI/UX

#935 feat: add i18n support for JamLanding component
  src/components/JamLanding.tsx
  src/i18n/locales/en/translation.json
Labels: v2
