Repository joinmarket-webui/jam, pull requests merged in 2025-08, with the labels that each got.

#956 feat: add FeeLimitDialog component for managing fee settings
  package.json
  src/components/Navbar.tsx
  src/components/settings/CollaboratorFeesForm.tsx
  src/components/settings/FeeLimitDialog.tsx
  src/components/settings/MiningFeesForm.tsx
  src/components/settings/Settings.tsx
  src/components/settings/TxFeeInputField.tsx
  src/components/ui/DevBadge.tsx
  src/components/ui/dialog.tsx
  src/components/ui/switch.tsx
  src/constants/jam.ts
  src/constants/jm.ts
  src/i18n/locales/en/translation.json
  src/lib/utils.test.ts
  src/lib/utils.ts
Labels: v2

#968 Fix: Pass client to Create wallet
  src/components/CreateWallet.tsx
Labels: v2

#950 chore(release): v0.4.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release

#972 chore(i18n): translations on Login and Create Wallet page
  src/App.tsx
  src/components/CreateWallet.tsx
  src/components/Login.tsx
  src/components/SwitchWallet.tsx
  src/components/earn/EarnPage.tsx
  src/components/receive/Receive.tsx
  src/components/send/SendPage.tsx
  src/components/settings/RescanChain.tsx
  src/components/settings/Settings.tsx
  src/components/sweep/SweepPage.tsx
  src/lib/utils.test.ts
  src/lib/utils.ts
  src/store/authStore.ts
Labels: tech dept, i18n, v2
