Repository joinmarket-webui/jam, pull requests merged in 2025-05, with the labels that each got.

#882 chore: update regtest deps
  docker/regtest/docker-compose-common.yml
  docker/regtest/docker-compose.yml
  docker/regtest/dockerfile-deps/joinmarket/directory_node/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/latest/default.cfg
  docker/regtest/dockerfile-deps/joinmarket/webui-standalone/default.cfg
  docker/regtest/dockerfile-deps/nginx/default.conf.template
  docker/regtest/generate-onion-address.sh
  package.json
Labels: dependencies, devtools

#894 added-rescan-progress-issue-744
  CHANGELOG.md
  package-lock.json
  package.json
  src/components/MainWalletView.tsx
  src/components/Navbar.tsx
  src/components/Wallets.tsx
  src/context/ServiceInfoContext.tsx
  src/i18n/locales/en/translation.json
  src/libs/JmWalletApi.ts
Labels: enhancement

#898 fix(ui): fidelity bond utxo row color in dark mode
  src/components/Send/ShowUtxos.module.css
Labels: bug, UI/UX

#899 chore: small cleanup after #894
  CHANGELOG.md
  src/context/ServiceInfoContext.tsx
Labels: tech dept

#897 fix(ui): fix button alignment in jar selection modal
  src/components/JarSelectorModal.tsx
  src/components/fb/SpendFidelityBondModal.tsx
Labels: bug, UI/UX

#878 feat: add color-coded checkboxes for UTXO states in Send view
  src/components/Send/ShowUtxos.module.css
Labels: enhancement, UI/UX
